baseURL = 'https://tech-horizon.netlify.app/'
title = 'Tech Horizon'
subtitle = 'Tech horizon - The latest version of future technologys endpoit'
theme = 'hugo-theme-itheme'
themesDir = 'themes'
defaultContentLanguage = "en"
disableKinds = ["taxonomyTerm"]
defaultContentLanguageInSubdir = true

[permalinks]
  en = "/en/posts/:slug/"
  uk = "/uk/posts/:slug/"

[languages]
  [languages.en]
    title = "Tech Horizon"
    languageName = "English"
    contentDir = "content/en"
    weight = 3
  [languages.uk]
    title = "Tech Horizon"
    languageName = "Українська"
    contentDir = "content/uk"
    weight = 1
  [languages.ru]
    title = "Tech Horizon"
    languageName = "Русский"
    contentDir = "content/ru"
    weight = 2


[params]
  defaultCover = 'https://source.unsplash.com/800x450/?{Blockchain}' # default cover image for post not setting cover
  email = 'long_py@proton.me' # the email address display in the footer
  [[params.socialMedia]] # custom social links display in the footer, you can add one or more
    name = 'Github'
    url = 'https://github.com/traffic-max'
  [[params.socialMedia]]
    name = 'Twitter'
    url = 'https://twitter.com/'
  [[params.blogroll]] # blogroll links display in the footer, you can add one or more
    name = 'Apple'
    url = 'https://Apple.com/'
  [[params.blogroll]]
    name = 'Google'
    url = 'https://Google.com/'

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[build]
  useResourceCache = true
  [build.resources]
    [build.resources.postCSS]
      outputStyle = "compressed"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 0

[[menu.main]]
  name = "About"
  url = "/en/about/"
  weight = 5
  language = "en"

[[menu.main]]
  name = "Про нас"
  url = "/uk/about/"
  weight = 6
  language = "uk"

[[menu.main]]
  name = "Articles"
  url = "/en/posts/"
  weight = 10
  language = "en"

[[menu.main]]
  name = "Статті"
  url = "/uk/posts/"
  weight = 11
  language = "uk"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
