baseURL = 'https://tech-horizon.netlify.app'
languageCode = 'en-us'
title = 'TechHorizon - Нові горизонти технічного світу'
theme = 'hugo-theme-itheme'
defaultContentLanguage = "en"
disableKinds = ["taxonomyTerm"]

[params]
  defaultCover = 'https://cdn.pixabay.com/photo/2023/04/20/20/01/sea-7940530_1280.jpg' # default cover image for post not setting cover
  email = 'long_py@proton.me' # the email address display in the footer
  [[params.socialMedia]] # custom social links display in the footer, you can add one or more
    name = 'Github'
    url = 'https://github.com/traffic-max'
  [[params.socialMedia]]
    name = 'Twitter'
    url = 'https://twitter.com/'
  [[params.blogroll]] # blogroll links display in the footer, you can add one or more
    name = 'Apple'
    url = 'https://Apple.com/'
  [[params.blogroll]]
    name = 'Google'
    url = 'https://Google.com/'

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[build]
  useResourceCache = true
  [build.resources]
    [build.resources.postCSS]
      outputStyle = "compressed"
