baseURL = 'https://tech-horizon.netlify.app'
languageCode = 'en-us'
title = 'Tech Horizon'
subtitle = 'Tech horizon - The latest versions of future technologys endpoit'
theme = 'hugo-theme-itheme'
defaultContentLanguage = "en"
disableKinds = ["taxonomyTerm"]

[params]
  defaultCover = 'https://cdn.pixabay.com/photo/2023/04/20/20/01/sea-7940530_1280.jpg' # default cover image for post not setting cover
  email = 'long_py@proton.me' # the email address display in the footer
  [[params.socialMedia]] # custom social links display in the footer, you can add one or more
    name = 'Github'
    url = 'https://github.com/traffic-max'
  [[params.socialMedia]]
    name = 'Twitter'
    url = 'https://twitter.com/'
  [[params.blogroll]] # blogroll links display in the footer, you can add one or more
    name = 'Apple'
    url = 'https://Apple.com/'
  [[params.blogroll]]
    name = 'Google'
    url = 'https://Google.com/'

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[build]
  useResourceCache = true
  [build.resources]
    [build.resources.postCSS]
      outputStyle = "compressed"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 0

[[menu.main]]
  name = "About"
  url = "about"
  weight = 5

[[menu.main]]
  name = "Blog"
  url = "post/"
  weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false